### PR TITLE
Removing the mandatory parameter 'Version' in ChocolateyPackage

### PR DESCRIPTION
**Pull request by Outek**
- Removing parameter

### CODE REVIEW

**Comment by Outek** [comment]
What do you think about to remove the mandatory parameter? In our case, we just want to ensure an application, but the version is not important.

**Comment by gaelcolas** [comment]
Yeah, that makes sense. And that should default to 'latest' if not present (choco will default to latest automatically anyway).

**Comment by Outek** [comment]
Do you think you can possibly merge this request?

**Comment by gaelcolas** [comment]
In principle, yes. I'm not ok with implementation at first sight.
I think the `Compare-SemVerVersion` should not be changed. The 'allow ensure present of any version' is a feature of the Resource (not that function).
I appreciate it's more code, it makes more sense to put it there so it'd probably be more maintainable in the long run.

**Comment by Outek** [comment]
What is your suggestion? Where would you put it?

**Comment by gaelcolas** [comment]
Probably around here: https://github.com/gaelcolas/Chocolatey/blob/master/Chocolatey/public/Test-ChocolateyPackageIsInstalled.ps1#L110-L123

If version is not specified in the DSC Resource, then all items of that package name are valid, so `$MatchingPackages = $InstalledPackages` Where
https://github.com/gaelcolas/Chocolatey/blob/master/Chocolatey/public/Test-ChocolateyPackageIsInstalled.ps1#L112

But I haven't thought that through either, there might be a thing or two to change in the Test-TargetResource.

**Pull request merged**
