### PR TITLE
Adding credentials parameter to ChocolateyPackage resource

### PR DESCRIPTION
**Pull request by raandree**
I have added the parameter only to the ChocolateyPackage resource to be able to move forward in the DscWorkshop. I can check and adapt other resources later.

Currently the build of https://github.com/AutomatedLab/CommonTasks fails as the parameter is not supported but required to use an artifacts feed hosted on Azure DevOps Server.

### CODE REVIEW

**Comment by raandree** [comment]
PSDscRunAsCredential is a well defined pattern. Using the name 'Credential' is a common practice and then the credentials are used for the main purpose of the cmdlet / DSC resource. In our case it is to get something from a repository. Install-Module works the same way, ActiveDirectoryDsc and xExchange as well. Even in your own cmdlet 'Install-ChocolateyPackage' you use the name 'Credential'.

**Comment by gaelcolas** [comment]
I'm not saying I'm right tho

**Comment by raandree** [comment]
I would suggest staying with 'Credential'. It matches the pattern other cmdlets and resources are using. The only source Chocolatey pulls data from is the repository so I guess it is pretty clear what the credentials are used for.

**Comment by gaelcolas** [comment]
Alright.

**Pull request merged**
